In [1]:
import pandas as pd

#### Procesamiento del dataset
___

In [8]:
# Lectura del dataset original
df = pd.read_csv("../data/raw/Características y composición del hogar.csv", sep=";") 
df

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
2,8369550,3,1,3,"472,1319014",3,2,2,1,16,...,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,NaN,NaN
3,8369550,4,1,4,"472,1319014",4,2,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235346,8489520,3,1,3,"19,04352805",3,1,2,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [34]:
# Filtro de variables
df_variables = df[["P6040", "P753S2", "P1897"]]
df_filtro = df_variables[
    (df_variables["P6040"] >= 18) &
    (df_variables["P753S2"] == 11001)
]

df_filtro.shape

(253, 3)

In [41]:
# Dataset sin filtro de municipio
df_variables = df[["P6040", "P1897"]]
df_filtro = df_variables[df_variables["P6040"] >= 18]

filtro = pd.DataFrame({
    "Población Total": [len(df)],
    "Población Mayor de Edad": [len(df_filtro)],
    "Porcentaje de la Muestra": [round(len(df_filtro) / len(df) * 100, 1)]
})

filtro

   Población Total  Población Mayor de Edad  Porcentaje de la Muestra
0           235350                   172025                      73.1

In [44]:
# Análisis de calidad
calidad_datos = pd.DataFrame({
    "No nulos": df_filtro.notna().sum(),
    "Nulos": df_filtro.isna().sum(),
    "% Nulos": (df_filtro.isna().sum() / len(df_filtro) * 100).round(1)
})
calidad_datos

       No nulos  Nulos  % Nulos
P6040    172025      0      0.0
P1897    172025      0      0.0

In [51]:
# Verificación de datos

pd.DataFrame({
    "min": df_filtro.min(),
    "max": df_filtro.max()
})

        min    max
P6040  18.0  108.0
P1897   0.0   10.0